sudo: false
language: node_js
script:
  - npm --silent run lint
  - npm --silent test
deploy:
  provider: heroku
  app: exerking
  api_key:
    secure: "sJpyUnudjY7OQM+pWANaJKoiG1dF5HJFnZrnOwYc5AL/6y5CRB/bBwt8Z+giF4CWmxzl3cndTQ9sfYWtpHz9SF9kGIzike0mhznp2a5fcAJF895HMj0Jrt8HP8aB5V1eJPytU6oxTmTnQD6n0hyBcwH79dPv7n9/bTYXUaWbkj+dPsgVrpjLszCg5gy7yRIeZrL9SgRegJ7hGDhJk59kUmfrK4wGycqIrFKqQPkRp3X1I23Z6w6m8c0ua6DOknz5rhs65HRazWBl5NTgebrt9iP/hBQ9nO76n6sAn4S4JnH8GMW4gvB7tUIcvRInz1slURPOtV6Z0O+SVqj/qBjXqN2du1cZ73xMtuBbiq+5POYkuvkQYwR69PNijy7jV9g2LpVebnknX9D/pEN8898V3ybeGP6TVo6eZonVJyawAhnUKm82Eq9smP+iBKMe7hqYXtj7AVWL3bRXtf18hdzCxbwZhUQNh6Vj7jFaAKgWEFF+QICRfKQumgIAa1hed4X4/o3HDT5eUhqITFewfXdRJLxOHNLCu7DiLqtFE57u1aUhWsZhPJa0rJYiusJkjW81vrq5gjUUXLjv4EXeQ36CYW/2l6u1m/L6UTQJJwLzdUBl08Wz+yAZCfVKrdlqJ5h5bMEYNYiDqcrDXNSelo+5AFgPbAABzuzdtIvYJKgHoQg="
