sudo: false
language: node_js
deploy:
  provider: heroku
  app: exerking
  api_key:
    secure: "DODwI0Q7eWEi++nJPDqmk/RfTxCoCeocZ5QLOE/6hE0CpXjx/zz6ZMooztPY29AFndyuP3Cwd3ebgUjo1/LTm11WgNgnJs2FHiBjEZ7d1F2K2vNUGKBML9bZsUCx1wIUIWJXd/S/pqC5rpTo5bqzMWyztUJYtSK5zudSP6nQ+TyCSPmaM0UgaD6qhwnHOGJqauz0Moo6mItR6Rt8fUN4SGSxQU1vELd/alU4y2Gk5d++KmuDp06vm5kRcwcgjzNGoUe04AettE9s9jTGQ8n0L4lp8FsPESOK0keg6YcBdDsC9MWXHPj3Uta9VExK0mgfCv3pEOEuJPAbSC6/M9TK4buSTb7ASdFCXokz7leKZIgAO9P/L1wRln9jkqZA28LVc16ktIty5ANlNnN/9LAWfS1jfX0LvqDrPf5oBzE9om9Ztm2WFh0kjyIxD59Jtw63AlmIvY9pSObJz3CkzKSF7Cc3tTDs/xGzfGxk16mbTy3dYl5L5cMyP1sMH3Fl8aTDmlY2z055r1thh4VFtZefjGRLn7ZBUysbKgzy2oDomyG4BFsTqIvnOq2SyqtPeboTpNmv+FfrFAodQpc/BV8u5Mbg8qGEOyoeiCnzsbdLJgWT9VIeTFMP4GKwPVEOBstGBgjNbCV8V2M37TUlhoOW3t/ntx3fV/ARHMfsTZlzi1k="
